Video Share Library Web Application/Controllers/AddVideoController.cs
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Web;
using System.Configuration;
using Video_Share_Library_Web_Application.Data;
using Video_Share_Library_Web_Application.Models;
using Microsoft.AspNetCore.Authorization;

namespace Video_Share_Library_Web_Application.Controllers
{
    [Authorize]
    public class AddVideoController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;

        public AddVideoController(ApplicationDbContext dbContext)
        {
            _dbcontext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadVideo(IFormFile file)
        {
            if(file == null || file.Length == 0)
            {
                return Content("file not selected");
            }

            var fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" +
                    Path.GetRandomFileName().Substring(0,4) + Path.GetExtension(file.FileName);

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "videos", fileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            var video = new VideoInfo
            {
                VideoName = file.FileName,
                VideoPath = "/videos/" + fileName,
                UploaderName = User.Identity.Name
            };

            _dbcontext.VideoInfo.Add(video);
            await _dbcontext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Video Share Library Web Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Video_Share_Library_Web_Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Video_Share_Library_Web_Application.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Video_Share_Library_Web_Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddVideo" asp-action="Index">Add Video</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Video_Share_Library_Web_Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>